### PR TITLE
fix(types): append declare module

### LINKED ISSUE #302: [v4] Accessing `$vfm` on template throws type error when use TypeScript
### Version

vue-final-modal: v4.0.0-rc.6
vue: v3.2.45"

### OS

Mac

### What Happen

截圖 2023-01-10 下午4 15 09

### What is Expected?

It should add type that `Vfm` to Vue's `ComponentCustomProperties`.

### PR DESCRIPTION
**Pull request by Mini-ghost**
Resolves #302

### CODE REVIEW

File: packages/vue-final-modal/src/index.ts [hunk 1]
```diff
@@ -30,3 +32,15 @@ export type { ModalBottomEmits } from './components/ModalBottom/ModalBottom.vue'
 
 /** Composables */
 export { useVfm, useModal, useVfmAttrs } from './useApi'
+
+declare module '@vue/runtime-core' {
+  export interface ComponentCustomProperties {
+    /**
+     * Vue Final Modal global state for the modal components and also provides
+     * functions that can be used to control the modal components. @see {Vfm}
+     */
```
Comment (hunterliu1003) [inline packages/vue-final-modal/src/index.ts:41]:
```suggestion
    /**
     * Access to the application's Vfm
     */
```

**Review by hunterliu1003 — APPROVED** [review]
